server:
  port: 8082

spring:
  application:
    name: product-service
  datasource:
    url: ${PRODUCT_DB_URL:jdbc:postgresql://localhost:5432/product_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  kafka:
    bootstrap-servers: ${KAFKA_URL:localhost:9092}
    consumer:
      group-id: product-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.type.mapping: >-
          orderCreated:com.project.productservice.events.OrderCreatedEvent,
          orderCancelled:com.project.productservice.events.OrderCancelledEvent

api:
  prefix: /api/v1

jwt:
  expiration: 2592000
  secretKey: ${JWT_SECRET}

services:
  user:
    url: ${USER_SERVICE_URL:http://localhost:8081}
